### PR TITLE
Deprecate log4go and fix gometalinter errors

### LINKED ISSUE #24: Several linter errors and warnings to be fixed
[`gometalinter`](https://github.com/alecthomas/gometalinter) is an exceptional tool for checking errors and warnings into a source code written in Go.

After running the tool for rqlite, I found that there are many small things to be fixed:

```
$ gometalinter ./...
main.go:101::error: possible formatting directive in Error call
main.go:119::error: possible formatting directive in Error call
command/execute_command.go:64::error: possible formatting directive in Error call
server/server.go:214::error: arg s.connectionString for printf verb %s of wrong type: func() string
server/server.go:240::error: possible formatting directive in Error call
server/server.go:482::error: possible formatting directive in Error call
db/db.go:15::warning: unused global variable dbName
main.go:78:14:warning: error return value not checked (os.MkdirAll(logFileDir, 0744))
main.go:101:13:warning: error return value not checked (log.Error("Unable to create path: %s", err.Error()))
main.go:103:16:warning: error return value not checked (defer f.Close())
main.go:105:24:warning: error return value not checked (pprof.StartCPUProfile(f))
main.go:114:12:warning: error return value not checked (log.Error("No data path supplied -- aborting"))
main.go:119:12:warning: error return value not checked (log.Error("Unable to create path: %s", err.Error()))
main.go:124:12:warning: error return value not checked (log.Error(s.ListenAndServe(join)))
main.go:141:16:warning: error return value not checked (go client.Post("https://logs-01.loggly.com/inputs/8a0edd84-92ba-46e4-ada8-c529d0f105af/tag/reporting/",)
command/execute_command.go:64:14:warning: error return value not checked (log.Error("Failed to rollback transaction: %s", err.Error))
command/execute_command.go:71:12:warning: error return value not checked (log.Error("Failed to start transaction:", err.Error()))
command/execute_command.go:77:13:warning: error return value not checked (log.Error("Failed to execute statement within transaction", err.Error()))
command/execute_command.go:83:12:warning: error return value not checked (log.Error("Failed to commit transaction:", err.Error()))
db/db.go:30:11:warning: error return value not checked (os.Remove(dbPath))
db/db.go:39:12:warning: error return value not checked (log.Error(err))
db/db.go:56:11:warning: error return value not checked (log.Warn("Query \"%s\" may modify the database", query))
db/db.go:60:12:warning: error return value not checked (log.Error("failed to execute SQLite query", err.Error()))
db/db.go:63:18:warning: error return value not checked (defer rows.Close())
db/db.go:77:13:warning: error return value not checked (log.Error("failed to scan SQLite row", err.Error()))
server/server.go:142:21:warning: error return value not checked (m.registry.Register("join.success", m.joinSuccess))
server/server.go:143:21:warning: error return value not checked (m.registry.Register("join.fail", m.joinFail))
server/server.go:144:21:warning: error return value not checked (m.registry.Register("query.Received", m.queryReceived))
server/server.go:145:21:warning: error return value not checked (m.registry.Register("query.success", m.querySuccess))
server/server.go:146:21:warning: error return value not checked (m.registry.Register("query.fail", m.queryFail))
server/server.go:147:21:warning: error return value not checked (m.registry.Register("execute.Received", m.executeReceived))
server/server.go:148:21:warning: error return value not checked (m.registry.Register("execute.tx.received", m.executeTxReceived))
server/server.go:149:21:warning: error return value not checked (m.registry.Register("execute.success", m.executeSuccess))
server/server.go:150:21:warning: error return value not checked (m.registry.Register("execute.fail", m.executeFail))
server/server.go:151:21:warning: error return value not checked (m.registry.Register("snapshot.created", m.snapshotCreated))
server/server.go:233:12:warning: error return value not checked (log.Error("Failed to create new Raft server", err.Error()))
server/server.go:240:12:warning: error return value not checked (log.Error("Error loading snapshot: %s", err.Error()))
server/server.go:244:20:warning: error return value not checked (s.raftServer.Start())
server/server.go:252:13:warning: error return value not checked (log.Error("Cannot join with an existing log"))
server/server.go:256:13:warning: error return value not checked (log.Error("Failed to join leader", err.Error()))
server/server.go:270:13:warning: error return value not checked (log.Error("Failed to join to self", err.Error()))
server/server.go:311:28:warning: error return value not checked (json.NewEncoder(&b).Encode(command))
server/server.go:316:23:warning: error return value not checked (defer resp.Body.Close())
server/server.go:396:10:warning: error return value not checked (w.Write([]byte(b)))
server/server.go:482:12:warning: error return value not checked (log.Error("Database mutation failed: %s", err.Error()))
server/server.go:498:10:warning: error return value not checked (w.Write([]byte(b)))
server/server.go:509:13:warning: error return value not checked (log.Error("failed to get " + k + " stats"))
server/server.go:516:9:warning: error return value not checked (w.Write(ensurePrettyPrint(req, statistics)))
server/server.go:531:9:warning: error return value not checked (w.Write(ensurePrettyPrint(req, diagnostics)))
server/server.go:542:9:warning: error return value not checked (w.Write(ensurePrettyPrint(req, info)))
server/statemachine.go:33:12:warning: error return value not checked (log.Error("Failed to save state: ", err.Error()))
server/statemachine.go:45:12:warning: error return value not checked (log.Error("Failed to recover state: ", err.Error()))
```

Many of them are not easy to fix, as they require bigger changes in the code, but the idea here is to decrease the length of this list, and try not to increment it on new changes. We could eventually add `gometalinter` as part of the CI system.

### PR DESCRIPTION
**Pull request by fern4lvarez**
Pending:
- [x] Fix gometalinter errors in `server` package (and fix #24)
- [x] Document `log` package

- ~~[ ] Normalize log messages (i.e. start all with capital letter, s/unable/failed, etc.)~~
- ~~[ ] Log to stderr when it comes to error logs (ignore if writing to log file)~~

Pull request powered by [oscillatingworks](http://oscillating.works).

### CODE REVIEW

**Comment by otoolep** [comment]
Makes sense @fern4lvarez -- is there any copyright we need to include, since we may just be copying some of the log4go code?

**Comment by fern4lvarez** [comment]
Where are we copying `log4go`'s code? Honestly I didn't take `log4go` code into account, the idea was to have a simple `log` package wrapper with a simple and intuitive interface.

**Comment by otoolep** [comment]
I wanted to check that we were not copying and pasting. If we are not, great.

**Comment by otoolep** [comment]
Is this still WIP? Build seems green now.

**Comment by fern4lvarez** [comment]
No, not copying at all, take it for granted :wink: 

> Is this still WIP? Build seems green now.

I'd like to complete first the pending bullets in the PR description, so we'd reduce drastically the number of warnings raised by gometalinter.

**Comment by fern4lvarez** [comment]
OK, I skip the two last bullets for now. But this should fix #25 and #24. Please review and merge if looks good to you.

File: db/db.go [hunk 1]
```diff
@@ -6,37 +6,36 @@ import (
...
+
+// RowResults is the list of results.
 type RowResults []map[string]string
 
 // New creates a new database. Deletes any existing database.
 func New(dbPath string) *DB {
-	log.Trace("Removing any existing SQLite database at %s", dbPath)
-	os.Remove(dbPath)
+	log.Tracef("Removing any existing SQLite database at %s", dbPath)
+	if err := os.Remove(dbPath); err != nil {
```
Comment (otoolep) [inline db/db.go]: Not a big deal, but really we want to check if the error is anything but "not exists". If so, then something has gone wrong, other we don't care.

File: db/db.go [hunk 2]
```diff
@@ -53,28 +52,33 @@ func (db *DB) Close() error {
...
+		}
+	}()
 
 	results := make(RowResults, 0)
 
 	columns, _ := rows.Columns()
 	rawResult := make([][]byte, len(columns))
 	dest := make([]interface{}, len(columns))
-	for i, _ := range rawResult {
+	for i := range rawResult {
```
Comment (otoolep) [inline db/db.go]: So we just get the index, if we assign to only 1 variable?

File: db/db.go [hunk 3]
```diff
@@ -88,55 +92,63 @@ func (db *DB) Query(query string) (RowResults, error) {
...
+	log.Debugf("Executed query successfully: %s", query)
 	return results, nil
 }
 
 // Execute executes the given sqlite statement, of a type that doesn't return rows.
 func (db *DB) Execute(stmt string) error {
+	var s string
+
 	_, err := db.dbConn.Exec(stmt)
-	log.Debug(func() string {
```
Comment (otoolep) [inline db/db.go]: If I recall correctly, this was done for a reason so that the strings are not actually created if logging is not in debug mode.

File: main.go [hunk 4]
```diff
@@ -134,10 +109,45 @@ func main() {
...
+	return f
+}
+
 func reportLaunch() {
 	json := fmt.Sprintf(`{"os": "%s", "arch": "%s", "app": "rqlite"}`, runtime.GOOS, runtime.GOARCH)
 	data := bytes.NewBufferString(json)
 	client := http.Client{Timeout: time.Duration(5 * time.Second)}
-	go client.Post("https://logs-01.loggly.com/inputs/8a0edd84-92ba-46e4-ada8-c529d0f105af/tag/reporting/",
-		"application/json", data)
+	go func() {
```
Comment (otoolep) [inline main.go]: Is this a lint requirement?

File: main.go [hunk 5]
```diff
@@ -134,10 +109,45 @@ func main() {
...
 }
 
+func closeFile(f *os.File) {
+	if err := f.Close(); err != nil {
+		log.Errorf("Unable to close file: %s", err.Error())
+		os.Exit(1)
+	}
+}
+
+func createFile(path string) *os.File {
```
Comment (otoolep) [inline main.go]: Did you hit some issues that triggered creation of this function?

File: server/server.go [hunk 6]
```diff
@@ -82,8 +88,8 @@ type Server struct {
 	dbPath      string
 	db          *db.DB
 	snapConf    *SnapshotConf
-	metrics     *ServerMetrics
-	diagnostics *ServerDiagnostics
+	metrics     *Metrics
```
Comment (otoolep) [inline server/server.go]: Nice, get rid of the `Server.Server....`.

**Comment by otoolep** [comment]
Thanks @fern4lvarez -- looks good. I have a few small questions.

File: db/db.go (hunk 2 above)
Comment (fern4lvarez) [inline db/db.go]: Yes, it only works for indexes. For elements of the array, a `for _, result := range ...` notation is needed. This is something that `gometalinter` complained about.

File: db/db.go (hunk 3 above)
Comment (otoolep) [inline db/db.go]: So if we put loads and loads of debug statements in, performance wouldn't be affected by all the string creation when not in debug mode. Probably not a real concern with rqlite.

Comment (fern4lvarez) [inline db/db.go]: Yeah, I see the point. I tried this, but somehow this internal log implementation failed to resolve the func() string when used as a parameter and I was getting a weird value (the func description). I can investigate deeper, there must be a walkaround... Please feel free to let me double check before merging, or go ahead and fix it afterwards.

File: main.go (hunk 4 above)
Comment (fern4lvarez) [inline main.go]: Yep, it is, and it's usual with `defer` and `go` statements. It's pretty common that one ignores the response (and thus the error checking) when using this statements on functions that return values, and the linter in this case complains. Do you see some negative impact involved in this change?

File: main.go (hunk 5 above)
Comment (fern4lvarez) [inline main.go]: See my comment below. `defer` and error checking ain't good friends, so I came up with this helper function.

Comment (fern4lvarez) [inline main.go]: Does it make sense to you? We can always create a new file in the root directory to store these helpers, e.g. `helpers.go`, and keep `main.go` cleaner.

File: server/server.go (hunk 6 above)
Comment (fern4lvarez) [inline server/server.go]: Indeed, it's a pretty common mistake. This one was also warned by `gometalinter`.

File: db/db.go (hunk 1 above)
Comment (fern4lvarez) [inline db/db.go]: kk, I can ignore this error using a `_ = os.Remove(...` notation, so the code reader knows that this function returns an error value, but it's unimportant, and make the linter happy.

Comment (fern4lvarez) [inline db/db.go]: Updated.

File: db/db.go (hunk 3 above)
Comment (fern4lvarez) [inline db/db.go]: Nice, I found what the issue was. Just pushed a new commit with the fixup.

**Comment by fern4lvarez** [comment]
Updated after comments. Let me know your thoughts, so I can clean up the commit history, i.e. squash Fixup commits before merging.

**Comment by fern4lvarez** [comment]
Done!

**Comment by otoolep** [comment]
Thanks again @fern4lvarez

**Comment by otoolep** [comment]
Unfortunately I had to revert this change as it causes rqlite to panic.

```
 $ go get github.com/otoolep/rqlite
~/r $ $GOPATH/bin/rqlite ~/node.1
2015/03/28 11:24:59 [INFO ] Raft random seed initialized
2015/03/28 11:24:59 [INFO ] Raft commands registered
panic: open /home/philip/node.1/name: not a directory

goroutine 1 [running]:
github.com/otoolep/rqlite/server.NewServer(0x7fff7ce15dff, 0x13, 0x8b8b30, 0x9, 0x64, 0x8bd090, 0x9, 0xfa1, 0x7f34929cbf58)
        /home/philip/r/src/github.com/otoolep/rqlite/server/server.go:200 +0x90e
main.main()
        /home/philip/r/src/github.com/otoolep/rqlite/main.go:97 +0x4c7

goroutine 6 [syscall]:
os/signal.loop()
        /home/philip/.gvm/gos/go1.4/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /home/philip/.gvm/gos/go1.4/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/philip/.gvm/gos/go1.4/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [runnable]:
database/sql.(*DB).connectionOpener(0xc2080561e0)
        /home/philip/.gvm/gos/go1.4/src/database/sql/sql.go:588
created by database/sql.Open
        /home/philip/.gvm/gos/go1.4/src/database/sql/sql.go:452 +0x31c
```

This is on me really, as I need to improve the test code significantly so something like this is caught by the CI system. The first step in that is fixing issue #27 , which will make testing much easier.

**Comment by otoolep** [comment]
The way of starting rqlite is described in the README, is a valid thing to do.

**Comment by fern4lvarez** [comment]
Uhm, sorry to hear this. I'll try to reproduce this and apply a fix, if possible. Of course reverting it was the best choice!

**Comment by otoolep** [comment]
No worries, it happens. I'll improve the unit test, so we can continue development and have the CI system help us catch this stuff earlier.
